#!/bin/bash

if (( $1 > 0 )); then
	export ARG=`Ruby -e "puts (1..$1).to_a.shuffle.join(' ')"`
	export ARGINC=`Ruby -e "puts (1..$1).to_a.join(' ')"`
	export ARGDEC=`Ruby -e "puts $1.downto(1).to_a.join(' ')"`
else
	export ARG=`Ruby -e "puts ($1..-1).to_a.shuffle.join(' ')"`
	export ARGINC=`Ruby -e "puts ($1..-1).to_a.join(' ')"`
	export ARGDEC=`Ruby -e "puts -1.downto($1).to_a.join(' ')"`
fi
